### ISSUE TITLE
Copy of  Lesson Details Not Syncing to Student Profile After Offline Play

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1386] opened 2024-04-03 04:02 UTC
**Description** 
After playing several lessons offline for 4-5 days and then reconnecting to the internet, the lesson details are not appearing under the student's profile in database.

**Comment by divyahariharan2103** [comment] 2024-04-08 04:55
Duplicate of 1380, closing the task

**Closed by divyahariharan2103** 2024-04-08 04:55 UTC
Labels: bug
