### ISSUE TITLE
Notification issue 

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1191] opened 2024-01-20 08:06 UTC
If we click on reward notification then it's not navigating to Avatar Page

https://github.com/chimple/cuba/assets/138564361/a884b8bc-fd99-4b3f-b115-41c2ffc656e0

**Comment by SWETHAKRISHNA2** [comment] 2024-03-12 03:16
If I click on reward notification , it is not connecting to avatar page

**Comment by akshattak** [comment] 2024-03-18 04:45
It will be done today- 18 March

**Comment by Pramodmarssun** [comment] 2024-04-03 04:06
Notification of colleting badges functionality is working when the app is closed as well as when student profile is signed out but when the app is running in the background it's now working

**Comment by Ashish1998** [comment] 2024-04-12 10:00
The issue is fixed can be moved to done.

**Closed** 2024-05-08 06:17 UTC
Labels: bug
