### ISSUE TITLE
Back button and text field is not working in homework screen

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#373] opened 2023-05-30 09:57 UTC

**Comment by Ashish1998** [comment] 2023-06-01 09:50
Still the issue is happening.

**Comment by Ashish1998** [comment] 2023-06-05 06:52
Here the text field and the text are coming at top of the screen in few devices.

![Screenshot_2023-06-05-12-17-44-329](https://github.com/chimple/cuba/assets/99384703/054cb137-8577-46d6-b406-51f479e8ab79)

**Comment by renukaj07** [comment] 2023-06-05 06:56
This issue was re-assigned to Alok

**Closed** 2023-06-08 09:21 UTC
